import{a as S,S as w,i as l}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",M="52810682-f1cccaa4d6041835a99124ea2";async function u(r,t=1){const a={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(q,{params:a})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:s,comments:b,downloads:v})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){f.innerHTML=""}function y(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function $(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const O=document.querySelector(".form"),P=document.querySelector("input[name='search-text']"),x=document.querySelector(".load-more");let c="",n=1,d=0;O.addEventListener("submit",A);x.addEventListener("click",D);async function A(r){if(r.preventDefault(),c=P.value.trim(),!!c){n=1,E(),L(),y();try{const t=await u(c,n);if(t.hits.length===0){l.info({message:"No images found."});return}h(t.hits),d=Math.ceil(t.totalHits/15),n<d&&$()}catch{l.error({message:"Error fetching data"})}finally{g()}}}async function D(){n+=1,y();try{const r=await u(c,n);h(r.hits),n>=d&&(L(),l.info({message:"We're sorry, but you've reached the end of search results."}));const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{l.error({message:"Error loading more images"})}finally{g()}}
//# sourceMappingURL=index.js.map
