import{a as S,S as q,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",B="52810682-f1cccaa4d6041835a99124ea2";async function u(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(M,{params:s})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:c,comments:v,downloads:w})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${c}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){f.innerHTML=""}function y(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function L(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const P=document.querySelector(".form"),O=document.querySelector("input[name='search-text']"),x=document.querySelector(".load-more");let l="",a=1,d=0;P.addEventListener("submit",A);x.addEventListener("click",D);async function A(r){if(r.preventDefault(),l=O.value.trim(),!l){n.warning({message:"Please enter a search term!",position:"topRight"});return}a=1,$(),b(),y();try{const t=await u(l,a);if(t.hits.length===0){n.info({message:"No images found for your request."});return}p(t.hits),d=Math.ceil(t.totalHits/15),a<d?L():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Error fetching data"})}finally{g()}}async function D(){a+=1,b(),y();try{const r=await u(l,a);p(r.hits),a>=d?n.info({message:"We're sorry, but you've reached the end of search results."}):L();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({message:"Error loading more images"})}finally{g()}}
//# sourceMappingURL=index.js.map
